CREATE TABLE [dbo].[tsys_NewsView] (
    [Id]           INT            IDENTITY (1, 1) NOT NULL,
    [TemplateID]   INT            NOT NULL,
    [Title]        VARCHAR (200)  COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [TitleTab]     NVARCHAR (50)  COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Url]          VARCHAR (200)  COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Content]      TEXT           COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Author]       NVARCHAR (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [From]         NVARCHAR (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Count]        INT            CONSTRAINT [DF_tsys_News_Count] DEFAULT ((0)) NOT NULL,
    [KeyWord]      VARCHAR (100)  COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Editor]       VARCHAR (50)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [IsCreate]     BIT            CONSTRAINT [DF_News_Created] DEFAULT ((0)) NULL,
    [SmallImg]     VARCHAR (100)  COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [BigImg]       VARCHAR (100)  COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [ShortContent] VARCHAR (500)  COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Speciality]   VARCHAR (100)  COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [IsCheck]      BIT            CONSTRAINT [DF_News_IsChecked] DEFAULT ((0)) NULL,
    [IsDel]        BIT            CONSTRAINT [DF_News_Del] DEFAULT ((0)) NULL,
    [IsCommend]    BIT            CONSTRAINT [DF_tsys_News_IsCommend] DEFAULT ((0)) NOT NULL,
    [PageCount]    INT            CONSTRAINT [DF_tsys_News_IsPaging] DEFAULT ((1)) NOT NULL,
    [FilePath]     VARCHAR (100)  COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [AddTime]      DATETIME       CONSTRAINT [DF_News_AddTime] DEFAULT (getdate()) NULL,
    [UpTime]       DATETIME       CONSTRAINT [DF_News_UpTime] DEFAULT (getdate()) NULL,
    [Field1]       VARCHAR (200)  COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Field2]       VARCHAR (200)  COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Field3]       VARCHAR (200)  COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    CONSTRAINT [PK_tsys_News] PRIMARY KEY CLUSTERED ([Id] ASC)
);

